### ISSUE TITLE
actix better than xactor

### ISSUE THREAD

**Issue by lygz5016** [sunli829/xactor-benchmarks#1]
|||Wait for response(ms)|Only send(ms)|
|---|---|---|---|
|1|actix|186|12|
|1|xactor|929|14|
|2|actix|183|12|
|2|xactor|865|25|
|3|actix|182|12|
|3|xactor|568|14|
|4|actix|184|12|
|4|xactor|614|18|
|5|actix|185|12|
|5|xactor|507|24|
|6|actix|180|12|
|6|xactor|899|23|

dependencies:
```
[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
xactor = "0.6.4"
actix = "0.10.0-a"
actix-rt = "1.0.0"
async-trait = "0.1.24"

[profile.release]
opt-level=3
debug=false
rpath=false
lto=true
```

**Comment by sunli829** [comment]
Thanks, I was testing on actix 0.9, and I upgraded to 0.10 to test again.😁

**Comment by sunli829** [comment]
What is your system environment? Xactor is much faster than actix on my Mac.
